export const movieGenres = [
  "All",
  "Action",
  "Adventure",
  "Animation",
  "Anime",
  "Comedy",
  "Crime",
  "Documentary",
  "Drama",
  "Family",
  "Fantasy",
  "Game Show",
  "Horror",
  "Lifestyle",
  "Music",
  "Musical",
  "Mystery",
  "Reality TV",
  "Romance",
  "Sci-Fi",
  "Seasonal",
  "Short",
  "Sport",
  "Thriller",
  "Western",
] as const

export type Genre = (typeof movieGenres)[number]