import type { Movie } from "./interfaces/Movie";

export const initialMovies: Movie[] = [
    {
      id: 1,
      title: "El Padrino",
      year: 1972,
      genre: "Drama",
      rating: 9.2,
      description: "La historia de una familia de la mafia italiana en Nueva York.",
      poster: "https://www.infobae.com/new-resizer/hiIfl67IpVcJFdCYJpJOoaGgStE=/arc-anglerfish-arc2-prod-infobae/public/Z7TNUJTHKJESBNNHCEGLCMKLWA.jfif",
      watchCount: 0,
      watchLater: false,
    },
    {
      id: 2,
      title: "Pulp Fiction",
      year: 1994,
      genre: "Crimen",
      rating: 8.9,
      description: "La vida de un boxeador, dos sicarios, la esposa de un gánster y dos bandidos se entrelaza en una historia de violencia y redención.",
      poster: "https://musicart.xboxlive.com/7/292c0b00-0000-0000-0000-000000000002/504/image.jpg",
      watchCount: 2,
      watchLater: false,
    },
    {
      id: 3,
      title: "El Señor de los Anillos",
      year: 2001,
      genre: "Fantasía",
      rating: 8.8,
      description: "Un hobbit debe destruir un anillo mágico para salvar la Tierra Media.",
      poster: "https://es.web.img2.acsta.net/c_310_420/medias/nmedia/18/89/67/45/20061512.jpg",
      watchCount: 0,
      watchLater: true,
    },
    {
      id: 4,
      title: "Inception",
      year: 2010,
      genre: "Ciencia Ficción",
      rating: 8.7,
      description: "Un ladrón que roba secretos del subconsciente durante el sueño.",
      poster: "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_.jpg",
      watchCount: 0,
      watchLater: false,
    },
    {
      id: 5,
      title: "Forrest Gump",
      year: 1994,
      genre: "Drama",
      rating: 8.8,
      description: "La vida extraordinaria de un hombre con discapacidad intelectual.",
      poster: "https://m.media-amazon.com/images/S/pv-target-images/9fe3eef6b0b80d9440cccaf618c2b7785a433b96a7812bb4e8e18945b4e7a231.jpg",
      watchCount: 1,
      watchLater: false,
    },
    {
      id: 6,
      title: "Matrix",
      year: 1999,
      genre: "Ciencia Ficción",
      rating: 8.7,
      description: "Un programador descubre que la realidad es una simulación.",
      poster: "https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
      watchCount: 0,
      watchLater: true,
    },
    {
      id: 7,
      title: "Titanic",
      year: 1997,
      genre: "Romance",
      rating: 7.9,
      description: "Una historia de amor a bordo del famoso barco condenado.",
      poster: "https://play-lh.googleusercontent.com/560-H8NVZRHk00g3RltRun4IGB-Ndl0I0iKy33D7EQ0cRRwH78-c46s90lZ1ho_F1so=w240-h480-rw",
      watchCount: 3,
      watchLater: false,
    },
    {
      id: 8,
      title: "Gladiador",
      year: 2000,
      genre: "Acción",
      rating: 8.5,
      description: "Un general romano busca venganza contra el emperador corrupto.",
      poster: "https://es.web.img3.acsta.net/medias/nmedia/18/70/92/02/20149073.jpg",
      watchCount: 0,
      watchLater: false,
    },
  ]