import type { Movie } from "../interfaces/Movie";
const path = "https://image.tmdb.org/t/p/original"

export const initialMovies: Movie[] = [
    {
      id: 1,
      title: "How to Train Your Dragon",
      year: 2025,
      genre: "Fantasy",
      rating: 8.153,
      description: "On the rugged isle of Berk, where Vikings and dragons have been bitter enemies for generations, Hiccup stands apart, defying centuries of tradition when he befriends Toothless, a feared Night Fury dragon. Their unlikely bond reveals the true nature of dragons, challenging the very foundations of Viking society.",
      poster: `${path}/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg`,
      backdrop: `${path}/7HqLLVjdjhXS0Qoz1SgZofhkIpE.jpg`,
      watchCount: 0,
      watchLater: false,
    },
    {
      id: 2,
      title: "M3GAN 2.0",
      year: 2025,
      genre: "Action",
      rating: 7.726,
      description: "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.",
      poster: `${path}/4a63rQqIDTrYNdcnTXdPsQyxVLo.jpg`,
      backdrop: `${path}/cEQMqB3ahd4mfeUN6VGC0ouVnZZ.jpg`,
      watchCount: 0,
      watchLater: false,
    },
    {
      id: 3,
      title: "Man with No Past",
      year: 2025,
      genre: "Action",
      rating: 6.8,
      description: "Un ladrón que roba secretos del subconsciente durante el sueño.",
      poster: `${path}/eWHvROuznSzcxBAAkzX1X0Rmzoe.jpg`,
      backdrop: `${path}/8or4S9BPhkeYK0vlKsPFee4JVWI.jpg`,
      watchCount: 0,
      watchLater: false,
    },
    {
      id: 4,
      title: "劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来",
      year: 2025,
      genre: "Animation",
      rating: 7.7,
      description: "As the Demon Slayer Corps members and Hashira engaged in a group strength training program, the Hashira Training, in preparation for the forthcoming battle against the demons, Muzan Kibutsuji appears at the Ubuyashiki Mansion. With the head of the Demon Corps in danger, Tanjiro and the Hashira rush to the headquarters but are plunged into a deep descent to a mysterious space by the hands of Muzan Kibutsuji.  The destination of where Tanjiro and Demon Slayer Corps have fallen is the demons' stronghold – the Infinity Castle. And so, the battleground is set as the final battle between the Demon Slayer Corps and the demons ignites.",
      poster: `${path}/aFRDH3P7TX61FVGpaLhKr6QiOC1.jpg`,
      backdrop: `${path}/1RgPyOhN4DRs225BGTlHJqCudII.jpg`,
      watchCount: 0,
      watchLater: false,
    },
    {
      id: 5,
      title: "Karate Kid: Legends",
      year: 2025,
      genre: "Science Fiction",
      rating: 7.257,
      description: "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
      poster: `${path}/AEgggzRr1vZCLY86MAp93li43z.jpg`,
      backdrop: `${path}/7Q2CmqIVJuDAESPPp76rWIiA0AD.jpg`,
      watchCount: 0,
      watchLater: false,
    },
    {
      id: 6,
      title: "Superman",
      year: 2025,
      genre: "Action",
      rating: 7.496,
      description: "Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.",
      poster: `${path}/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg`,
      backdrop: `${path}/ApRxyHFuvv5yghedxXPJSm9FEDe.jpg`,
      watchCount: 0,
      watchLater: false,
    },
    {
      id: 7,
      title: "Ice Road: Vengeance",
      year: 2025,
      genre: "Action",
      rating: 6.988,
      description: "Big rig ice road driver Mike McCann travels to Nepal to scatter his late brother’s ashes on Mt. Everest. While on a packed tour bus traversing the deadly 12,000 ft. terrain of the infamous Road to the Sky, McCann and his mountain guide encounter a group of mercenaries and must fight to save themselves, the busload of innocent travelers, and the local villagers’ homeland.",
      poster: `${path}/cQN9rZj06rXMVkk76UF1DfBAico.jpg`,
      backdrop: `${path}/962KXsr09uK8wrmUg9TjzmE7c4e.jpg`,
      watchCount: 0,
      watchLater: false,
    },
    {
      id: 8,
      title: "Lilo & Stitch",
      year: 2025,
      genre: "Animation",
      rating: 7.3,
      description: "The wildly funny and touching story of a lonely Hawaiian girl and the fugitive alien who helps to mend her broken family.",
      poster: `${path}/c32TsWLES7kL1uy6fF03V67AIYX.jpg`,
      backdrop: `${path}/7Zx3wDG5bBtcfk8lcnCWDOLM4Y4.jpg`,
      watchCount: 0,
      watchLater: false,
    },
  ]